<?php
include("../includes/config.inc.php"); 
include("../includes/crosssite.inc.php"); 
$cust_id = mysql_real_escape_string($_POST['cust_id']);
$lead_gen = mysql_real_escape_string($_POST['lead_gen']);
$service_exe = mysql_real_escape_string($_POST['service_exe']);
$generate_date = mysql_real_escape_string($_POST['generate_date']);
$duedate = mysql_real_escape_string($_POST['duedate']);
/*echo $cust_id;*/
error_reporting(0);
$linkSQL = "Select B.invoiceId as estimateId, B.invoiceType as invoiceType, A.cust_id as cust_id, 	
			C.GeneratedDate as generatedDate, B.dueDate as duedate, D.Company_Name as companyName,
			B.discountedAmount as discount, D.District_id as district, A.telecaller_id as leadgenId,
			E.service_executive as serviceExecutive, D.Address as address, D.Mobile as mobile,
			B.generatedAmount as generatedAmount
			from tbl_customer_master as A
			inner join tbl_invoice_master as B
			on A.cust_id = B.customerId
			inner Join tblesitmateperiod as C
			on B.intervalId = C.intervalId
			INNER JOIN tblcallingdata as D 
			ON A.callingdata_id = D.id 
			LEFT OUTER JOIN tbl_assign_customer_branch as E 
			ON A.cust_id = E.cust_id
			where (B.invoiceFlag = 'N' or B.invoiceFlag = 'p')";
			// B.paymentStatusFlag = 'A'
			// And 
// echo $linkSQL;

if ( ($cust_id != 0) or ($lead_gen != 0) or ($service_exe !=0) or ($generate_date != '') or ($duedate != '')){
	$linkSQL  = $linkSQL." AND ";	
	// echo $linkSQL;
}
$counter = 0;

if ( $cust_id != 0) {
	if ($counter > 0 )
	 	$linkSQL =$linkSQL.' AND ';
	$linkSQL  =$linkSQL." A.cust_id = '$cust_id'";
	$counter+=1;
	// echo $linkSQL;
}

if ( $lead_gen != 0) {
	if ($counter > 0 )
	 	$linkSQL =$linkSQL.' AND ';
	$linkSQL  =$linkSQL." A.telecaller_id = '$lead_gen'";
	$counter+=1;
	// echo $linkSQL;
}
if ( $service_exe != 0) {
	if ($counter > 0 )
	 	$linkSQL =$linkSQL.' AND ';
	$linkSQL  =$linkSQL." E.service_executive = '$service_exe'";
	$counter+=1;
	// echo $linkSQL;
}
if ( $generate_date != '') {
	if ($counter > 0 )
	 	$linkSQL =$linkSQL.' AND ';
	$linkSQL  =$linkSQL." C.GeneratedDate = '$generate_date'";
	$counter+=1;
	// echo $linkSQL;
}
if ( $duedate != '') {
	if ($counter > 0 )
	 	$linkSQL =$linkSQL.' AND ';
	$linkSQL  =$linkSQL." B.dueDate = '$duedate'";
	$counter+=1;
	// echo $linkSQL;
}
$oRS = mysql_query($linkSQL);
	if(mysql_num_rows($oRS)>0){
?>
	
		<table border="0" class="table table-hover table-bordered" id="example"> 
		 <thead>
		 	<tr>
		      	<th><small>S.No.</small></th>  
		        <th><small>Estimate Id</small></th> 
		        <th><small>Customer Id</small></th> 
				<th><small>Estimate Type</small></th>
				<th><small>Period</small></th>
		      	<th><small>Customer Name</small></th>  
		      	<th><small>Address</small></th>
		      	<th><small>Mobile</small></th> 
		      	<th><small>District</small></th>
		      	<th><small>Lead generated by</small></th>
		      	<th><small>Service Executive</small></th>
		      	<th><small>Generated Date</small></th>
		        <th><small>Due Date</small></th>
		      	<th><small>Generated Amount</small></th> 
		        <th><small>Discount Amount</small></th> 
		        <th><small>Payble Balance</small></th>
		        <!-- <th><small>Action</small></th> -->
				<th><small>Status</small></th>
	      	</tr>  
		 </thead>  
		 <tbody>
         <?php
		 $kolor=1;
	 	 if(mysql_num_rows($oRS)>0){
  			while ($row = mysql_fetch_array($oRS)){
 	  	 ?>
         <tr>
      	 	<td><small><?php print $kolor++;?>.</small></td>
	  		<td><small><?php echo stripslashes($row["estimateId"]);?></small></td>
	  		<td><small><?= $row['cust_id']; ?></small></td>
      		<td><small>
		  		<?php if ($row["invoiceType"] == "A"){ echo 'Rental';} elseif($row["invoiceType"] == "B") { echo 'Device';}  ?>
        		</small>
        	</td>
        	<td><small><strong>From:</strong> 
	        	<?php echo date("d-m-Y", strtotime(payment_from($row["estimateId"])));?> 
	        	<strong>To:</strong> 
	        	<?php echo date("d-m-Y", strtotime(payment_to($row["estimateId"])));?>
        	</small></td>
			<td><small><?php echo $row['companyName']; ?></small></td>
			<td><small><?php echo $row['address']; ?></small></td>
			<td><small><?php echo $row['mobile']; ?></small></td>
			<td><small><?php echo getdistrict($row['district']); ?></small></td>
			<td><small><?php echo gettelecallername($row['leadgenId']); ?></small></td>
			<td><small><?php echo gettelecallername($row['serviceExecutive']); ?></small></td>
	      	<td><small><?php echo date("d-m-Y", strtotime(stripslashes($row["generatedDate"])));?> </small></td>
	        <td class="<?php if(strtotime($row["duedate"]) < strtotime(date("Y-m-d"))) echo 'datecolor' ?>">
	        <small><?php echo date("d-m-Y", strtotime(stripslashes($row["duedate"]))); ?></small></td>
	        <td><small><?php echo stripslashes($row["generatedAmount"]);?></small></td>
	        <td><small><?php if($row["discountedAmount"]==0)
						{
							echo "N/A";
						}
					  else
						{
							echo stripcslashes($row["discountedAmount"]);	
						}
				?>			
				</small>
			</td>
	        <td><strong><span class="label label-success"><?php echo $row["generatedAmount"] - $row["discountedAmount"]; ?></span></strong></td>
		    <td>
	    	<?php 
	    	$today = time();
	    	$from_due_date =  date("d-m-Y", strtotime(payment_from($row["estimateId"])));
	    	$your_date = strtotime($from_due_date);
			$datediff = $today - $your_date;
			$total_days = floor($datediff / (60 * 60 * 24));
			// echo $total_days;
			if(45 < $total_days ){
				echo '<span class="label label-danger">Overdue</span>';
			}
			else if(45 > $total_days){
				echo '<span class="label label-warning">Pending</span>';
			}
	    	?>	    		
	    	</td>
      	
		</tr>
        <?php 
           	}
            echo "</tbody>
				</table>";
          }
        }
	 else
       echo "<h3><font color=red>No records found !</h3></font>";
?>
