<?php 
include("../includes/config.inc.php"); 
//include("includes/crosssite.inc.php"); 
$cust_id_D = mysql_real_escape_string($_POST['cust_id_D']);
$lead_gen_D = mysql_real_escape_string($_POST['lead_gen_D']);
$service_exe_D = mysql_real_escape_string($_POST['service_exe_D']);
error_reporting(0);
$linkSQL = "SELECT D.callingdata_id as callingDateId, D.cust_id as custId, A.vehicle_no vehicleNo, 
            SUM(C.plan_rate) as deviceAmt, A.installation_date as activationDate, 
            F.service_branchId as assignBranch, D.telecaller_id referBy, 
            F.service_area_manager as areaManager, F.service_executive as serviceExecutive, 
            A.imei_no as imeiNo, A.mobile_no as mobileNo, A.id as vehicleId
            FROM tbl_gps_vehicle_master as A 
            INNER JOIN tbl_gps_vehicle_payment_master as B 
            ON A.id = B.Vehicle_id
            INNER JOIN tblplan as C 
            ON B.device_amt = C.id
            INNER JOIN tbl_customer_master as D 
            ON B.cust_id = D.cust_id 
            INNER JOIN tbl_device_master as E 
            ON A.device_id = E.id
            LEFT OUTER JOIN tbl_assign_customer_branch as F 
            ON D.cust_id = F.cust_id
           
            WHERE A.activeStatus = 'Y' 
            AND B.device_type = '1'
            AND A.devicePaymentStatus <> 'F' 
            AND B.PlanactiveFlag ='Y'
            GROUP BY D.callingdata_id
            order by A.installation_date";
            // AND B.devicepaymentStatus <>'A'
// exit();
$stockArr=mysql_query($linkSQL);

?>
        	<table class="table table-hover table-bordered" id="example">
                <thead>
                	<tr>
                        <th><small>S. No.</small></th>
                        <th><small>Follow-Up</small></th>
                        <th><small>Estimate Type</small></th>
                        <th><small>Customer Id</small></th>
                        <th><small>Company Name</small></th>
                        <th><small>Vehcile Details</small></th>
                        <th><small>Adress & Contact No</small></th>
                        <th><small>District</small></th>
                        <th><small>Lead generated by</small></th>
                        <th><small>Service Executive</small></th>
                        <th><small>Payble Balance</small></th>

                        <th><small>Status</small></th>
                    </tr>
                </thead>
                <tbody>
                <?php
                if(mysql_num_rows($stockArr)>0){
        	  		$kolor =1;
        		    while ($row = mysql_fetch_array($stockArr)){
     		  	?>
                    <tr>
                        <td><small><?php print $kolor++;?>.</small></td>
                        <td><small>
                            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" 
                            data-target=".bs-example-modal-lg" onclick="follow_up_rent(<?php echo stripslashes($row["estimateId"]);?>);">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            </button></small></td>
                        <td><small>Device</small></td>
                        <td><small><?php echo stripslashes($row["custId"]);?></small></td>
            			<td><small><?php echo getOraganization(stripslashes($row["callingDateId"]));?></small></td>
                        <td><small><?php echo stripslashes($row["custId"]);?></small></td>
                        <td><small><?php echo getCustomerAddress($row["callingDateId"]);?></small></td>
                        <td><small><?php echo getCustomerDistrict($row["callingDateId"]);?></small></td>
                        <td><small><?php echo gettelecallername(stripslashes($row["referBy"]));?></small></td>
            			<td><small><?php echo gettelecallername(stripslashes($row["serviceExecutive"]));?></small></td>
                        <td><span class="label label-success"><?php echo stripslashes($row["deviceAmt"]);?></span></td>
                       
                        <td><?php 
                            $today = time();
                            $activationDate =  date("d-m-Y", strtotime($row["activationDate"]));
                            $your_date = strtotime($activationDate);
                            $datediff = $today - $your_date;
                            $total_days = floor($datediff / (60 * 60 * 24));
                            // echo $total_days;
                            if(45 < $total_days ){
                                echo '<span class="label label-danger">Overdue</span>';
                            }
                            else if(45 > $total_days){
                                echo '<span class="label label-warning">Pending</span>';
                            }
                            ?></td>
                    </tr>
                <?php 
    			   }
                   echo "</tbody>
                        </table>";
                }
                else{
                    echo "<center><h3 style='color:red'>No Records found !</h3></center>";
                }
    		   ?>
            
